name: DB OPERATIONS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          cache: 'npm'
        
      - name: Install dependencies
        run: npm ci
        
      - name: Compile sources
        run: npm run build

      - name: 'GCP auth for env'
        id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
         credentials_json: '${{ secrets.SERVICE_ACCOUNT }}'

      - name: Create env file
        run: node ./dist/build/get-env.js

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: sources
          path: |
            ./
            !node_modules
  migrate:
    runs-on: ubuntu-latest
    needs: build
    env:
      NODE_ENV: migration
    steps:
      - name: Download compiled sources
        uses: actions/download-artifact@v3
        with:
          name: sources

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.SERVICE_ACCOUNT }}'

      - name: Cloud SQL Proxy
        uses: mattes/gce-cloudsql-proxy-action@v1
        with:
          creds: '${{ secrets.SERVICE_ACCOUNT }}'
          instance: clean-wonder-346011:europe-west4:core-db
          port: 3306

      - name: Migrate DB
        run: npm run migration:up

  seed:
    runs-on: ubuntu-latest
    needs: migrate
    steps:
      - name: Download compiled sources
        uses: actions/download-artifact@v3
        with:
          name: sources

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.SERVICE_ACCOUNT }}'

      - name: Cloud SQL Proxy
        uses: mattes/gce-cloudsql-proxy-action@v1
        with:
          creds: '${{ secrets.SERVICE_ACCOUNT }}'
          instance: clean-wonder-346011:europe-west4:core-db
          port: 3306

      - name: Seed DB
        run: npm run seed:up
